#!/usr/bin/env bash
ask_value(){ local var prompt default secret current value; var="$1"; prompt="$2"; default="${3:-}"; secret="${4:-no}"; current="${!var:-}"; [[ -z "$current" && -n "$default" ]] && current="$default"; if [[ "$secret" == yes ]]; then if [[ -n "$current" ]]; then read -rsp "$prompt [saved, Enter=keep]: " value || true; echo; [[ -n "$value" ]] && printf -v "$var" '%s' "$value"; else read -rsp "$prompt: " value || true; echo; printf -v "$var" '%s' "$value"; fi; else read -rp "$prompt${current:+ [$current]}: " value || true; printf -v "$var" '%s' "${value:-$current}"; fi; }
ask_optional(){ local var prompt current value; var="$1"; prompt="$2"; current="${!var:-}"; read -rp "$prompt${current:+ [$current]} (Enter=keep, -=disable): " value || true; [[ "$value" == - ]] && value="" || value="${value:-$current}"; printf -v "$var" '%s' "$value"; }

configure_wizard(){
  require_root; try_extract_php_config; header
  echo "Configuration wizard — secrets are never passed as CLI arguments."; echo
  [[ -z "$DB_PASS" ]] && DB_PASS="$(rand_hex 16)"
  [[ -z "$WEBHOOK_SECRET" ]] && WEBHOOK_SECRET="$(rand_hex 20)"
  [[ -z "$TELEGRAM_WEBHOOK_SECRET" ]] && TELEGRAM_WEBHOOK_SECRET="$(rand_hex 20)"
  [[ -z "$SWAPWALLET_CALLBACK_SECRET" ]] && SWAPWALLET_CALLBACK_SECRET="$(rand_hex 20)"
  ask_value DOMAIN "Domain (without https)"
  ask_value BOT_TOKEN "Telegram bot token" "" yes
  ask_value BOT_USERNAME "Bot username without @"
  ask_value ADMIN_IDS "Admin Telegram IDs, comma separated"
  ask_value SUPPORT_USERNAME "Support username" "BlueGateSupport"
  ask_value REPO_URL "Git repository" "$DEFAULT_REPO_URL"
  ask_value APP_DIR "Install directory" "$DEFAULT_APP_DIR"
  ask_value DB_NAME "Database name" "bluegate_platform"
  ask_value DB_USER "Database user" "bluegate_user"
  ask_value DB_PASS "Database password" "" yes
  ask_value BRAND_NAME "Brand name" "BlueGate"
  ask_value THEME_COLOR "Theme color" "#1d9bf0"
  ask_optional FORCE_JOIN_CHANNEL "Force-join channel"
  ask_optional RESEND_API_KEY "Resend API key"
  ask_optional RESEND_FROM_EMAIL "Resend sender"
  ask_value ENABLE_SSL "Enable SSL? yes/no" "yes"
  [[ "${ENABLE_SSL,,}" =~ ^(yes|y)$ ]] && ask_optional SSL_EMAIL "Let's Encrypt email"
  ask_value BACKUP_KEEP "Release backups to keep" "5"
  ask_value DB_BACKUP_DAYS "DB backup retention days" "14"
  validate_domain "$DOMAIN" || { fail "Invalid domain"; return 1; }
  validate_db_identifier "$DB_NAME" || { fail "Invalid DB name"; return 1; }
  validate_db_identifier "$DB_USER" || { fail "Invalid DB user"; return 1; }
  [[ "$(admin_array_php)" != "[]" ]] || { fail "At least one numeric ADMIN_ID is required"; return 1; }
  save_env
  ok "Configuration saved to $ENV_FILE"
}

generate_config(){
  [[ -d "$APP_DIR" ]] || { fail "App directory missing"; return 1; }
  [[ -n "$DOMAIN" && -n "$BOT_TOKEN" && -n "$BOT_USERNAME" && -n "$ADMIN_IDS" ]] || { fail "Required settings missing; run bluegate configure"; return 1; }
  local arr="$(admin_array_php)"
  cat > "$APP_DIR/config.php" <<PHP
<?php
// Generated by BlueGate CLI. Keep this file private.
\$BOT_TOKEN = '$(php_escape "$BOT_TOKEN")';
\$BOT_USERNAME = '$(php_escape "$BOT_USERNAME")';
\$ADMIN_IDS = ${arr};
\$SUPPORT_USERNAME = '$(php_escape "$SUPPORT_USERNAME")';
\$TIMEZONE = 'Europe/Istanbul';
\$PUBLIC_BASE_URL = 'https://$(php_escape "$DOMAIN")';
\$WEBHOOK_SECRET = '$(php_escape "$WEBHOOK_SECRET")';
\$TELEGRAM_WEBHOOK_SECRET = '$(php_escape "$TELEGRAM_WEBHOOK_SECRET")';
\$SWAPWALLET_CALLBACK_SECRET = '$(php_escape "$SWAPWALLET_CALLBACK_SECRET")';
\$MINIAPP_URL = 'https://$(php_escape "$DOMAIN")/miniapp/';
\$WEB_ALLOWED_ORIGIN = '';
\$DB_HOST = 'localhost';
\$DB_NAME = '$(php_escape "$DB_NAME")';
\$DB_USER = '$(php_escape "$DB_USER")';
\$DB_PASS = '$(php_escape "$DB_PASS")';
\$START_REWARD = 2000;
\$PURCHASE_REWARD = 10000;
\$MISSION_1_TARGET = 1; \$MISSION_1_REWARD = 3000;
\$MISSION_2_TARGET = 3; \$MISSION_2_REWARD = 10000;
\$MISSION_3_TARGET = 5; \$MISSION_3_REWARD = 25000;
\$SPIN_REFERRALS_PER_CHANCE = 5;
\$SPIN_REWARDS = [
 ['title'=>'💰 ۳,۰۰۰ تومان اعتبار BlueGate','amount'=>3000,'weight'=>35],
 ['title'=>'💰 ۵,۰۰۰ تومان اعتبار BlueGate','amount'=>5000,'weight'=>30],
 ['title'=>'💰 ۱۰,۰۰۰ تومان اعتبار BlueGate','amount'=>10000,'weight'=>18],
 ['title'=>'💰 ۲۰,۰۰۰ تومان اعتبار BlueGate','amount'=>20000,'weight'=>7],
 ['title'=>'🎁 سرویس تست هدیه','amount'=>0,'weight'=>10,'notify_admin'=>true],
];
\$CUSTOM_CODE_MIN_REFERRALS = 3;
\$FORCE_JOIN_CHANNEL = '$(php_escape "$FORCE_JOIN_CHANNEL")';
\$DEFAULT_THEME_COLOR = '$(php_escape "$THEME_COLOR")';
\$BRAND_NAME = '$(php_escape "$BRAND_NAME")';
\$PAYMENT_INSTRUCTIONS = 'اطلاعات پرداخت را از پنل مدیریت تنظیم کنید. بعد از پرداخت، کاربر می‌تواند رسید را ارسال کند.';
\$CARD_ACCOUNTS = [];
\$STARS_RATE_TOMAN = 3200; \$STARS_RATE_MODE='auto'; \$STARS_BASE_USDT=0.016; \$STARS_RATE_MARKUP_PERCENT=0;
\$CRYPTO_RATE_SOURCE='auto'; \$CRYPTO_RATE_MARKUP_PERCENT=1; \$CRYPTO_RATE_PROVIDER_PRIORITY='wallex,ramzinex,nobitex'; \$CRYPTO_RATE_REFRESH_INTERVAL_SECONDS=600;
\$CRYPTO_MANUAL_RATES=['USDT'=>0,'TRX'=>0,'TON'=>0]; \$TRONSCAN_API_KEY=''; \$TONCENTER_API_KEY='';
\$RESEND_API_KEY='$(php_escape "$RESEND_API_KEY")'; \$RESEND_FROM_EMAIL='$(php_escape "$RESEND_FROM_EMAIL")';
PHP
  php -l "$APP_DIR/config.php" >/dev/null
  chmod 640 "$APP_DIR/config.php"; chown root:www-data "$APP_DIR/config.php"
}

create_database(){
  validate_db_identifier "$DB_NAME" && validate_db_identifier "$DB_USER" || return 1
  systemctl start mariadb
  local pe="$(sql_escape "$DB_PASS")"
  mysql_root <<SQL
CREATE DATABASE IF NOT EXISTS \`${DB_NAME}\` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
CREATE USER IF NOT EXISTS '${DB_USER}'@'localhost' IDENTIFIED BY '${pe}';
ALTER USER '${DB_USER}'@'localhost' IDENTIFIED BY '${pe}';
GRANT ALL PRIVILEGES ON \`${DB_NAME}\`.* TO '${DB_USER}'@'localhost';
FLUSH PRIVILEGES;
SQL
}
run_migrations(){ [[ -f "$APP_DIR/public/install.php" ]] || { fail "Migration entrypoint missing"; return 1; }; runuser -u www-data -- php "$APP_DIR/public/install.php"; }
