<?php
/** Official Remnawave backend API connector (Phase 8, API token auth). */
final class BlueGateRemnawaveProvider extends BlueGateAbstractProvider {
    private string $base; private array $meta; private string $token;
    public function __construct(array $provider){parent::__construct($provider);$this->base=rtrim((string)($provider['base_url']??''),'/');$this->meta=json_decode((string)($provider['metadata_json']??'{}'),true)?:[];$this->token=(string)(bluegate_decrypt_secret($provider['api_token_encrypted']??null)??'');if($this->token==='')throw new RuntimeException('REMNAWAVE_API_TOKEN_REQUIRED');}
    public function driver(): string{return 'remnawave';}
    private function req(string $method,string $path,$body=null): array{if(!function_exists('curl_init'))throw new RuntimeException('PHP_CURL_REQUIRED');$ch=curl_init($this->base.$path);$h=['Accept: application/json','Authorization: Bearer '.$this->token];if($body!==null)$h[]='Content-Type: application/json';curl_setopt_array($ch,[CURLOPT_RETURNTRANSFER=>true,CURLOPT_CUSTOMREQUEST=>$method,CURLOPT_HTTPHEADER=>$h,CURLOPT_CONNECTTIMEOUT=>(int)($this->meta['connect_timeout']??8),CURLOPT_TIMEOUT=>(int)($this->meta['request_timeout']??20),CURLOPT_SSL_VERIFYPEER=>($this->meta['verify_tls']??true)!==false,CURLOPT_SSL_VERIFYHOST=>(($this->meta['verify_tls']??true)!==false)?2:0]);if($body!==null)curl_setopt($ch,CURLOPT_POSTFIELDS,json_encode($body,JSON_UNESCAPED_SLASHES|JSON_UNESCAPED_UNICODE));$raw=curl_exec($ch);$err=curl_error($ch);$code=(int)curl_getinfo($ch,CURLINFO_RESPONSE_CODE);curl_close($ch);if($raw===false||$err)throw new RuntimeException('REMNAWAVE_NETWORK:'.$err);$j=json_decode($raw,true);if($code<200||$code>=300)throw new RuntimeException('REMNAWAVE_HTTP_'.$code.':'.mb_substr(is_array($j)?json_encode($j):$raw,0,600));return is_array($j)?$j:['raw'=>$raw];}
    private function unwrap(array $r){return isset($r['response'])?$r['response']:$r;}
    public function testConnection(): array{$t=microtime(true);try{$r=$this->req('GET','/api/users?size=1&start=0');return['ok'=>true,'status'=>'online','latency_ms'=>(int)round((microtime(true)-$t)*1000),'message'=>'Connected via official Remnawave API token','details'=>['api'=>'/api/users']];}catch(Throwable $e){return['ok'=>false,'status'=>'offline','latency_ms'=>(int)round((microtime(true)-$t)*1000),'message'=>$e->getMessage()];}}
    public function listInbounds(): array{$r=$this->unwrap($this->req('GET','/api/internal-squads'));$list=$r['internalSquads']??$r['internal_squads']??$r;if(!is_array($list))return[];$out=[];foreach($list as$s){if(!is_array($s))continue;$id=(string)($s['uuid']??'');if($id==='')continue;$out[]=['id'=>$id,'tag'=>$id,'remark'=>(string)($s['name']??$id),'protocol'=>'internal-squad','inbounds'=>$s['inbounds']??[]];}return$out;}
    public function getClient(string $externalId): array{$path=preg_match('/^[0-9a-f-]{36}$/i',$externalId)?'/api/users/'.rawurlencode($externalId):'/api/users/by-username/'.rawurlencode($externalId);$u=$this->unwrap($this->req('GET',$path));return is_array($u)?$u:[];}
    private function isoExpiry(array $r): string{$x=$r['expires_at']??$r['expireAt']??null;if(!$x)return gmdate('c',time()+30*86400);$ts=is_numeric($x)?(int)$x:strtotime((string)$x);return gmdate('c',$ts>0?$ts:time()+30*86400);}
    private function createPayload(array $r): array{$username=trim((string)($r['email']??$r['external_username']??''));if($username==='')throw new RuntimeException('REMNAWAVE_USERNAME_REQUIRED');$cfg=is_array($r['provider_config']??null)?$r['provider_config']:[];$targets=$r['inbound_ids']??[];if(!is_array($targets))$targets=preg_split('/\s*,\s*/',(string)$targets,-1,PREG_SPLIT_NO_EMPTY)?:[];$squads=$cfg['active_internal_squads']??$cfg['activeInternalSquads']??$targets;return['username'=>$username,'status'=>'ACTIVE','trafficLimitBytes'=>max(0,(int)($r['traffic_limit_bytes']??0)),'trafficLimitStrategy'=>(string)($cfg['traffic_limit_strategy']??'NO_RESET'),'expireAt'=>$this->isoExpiry($r),'description'=>(string)($r['comment']??'BlueGate'),'telegramId'=>!empty($r['tg_id'])?(int)$r['tg_id']:null,'hwidDeviceLimit'=>isset($r['limit_hwid'])?(int)$r['limit_hwid']:null,'activeInternalSquads'=>array_values(array_filter(array_map('strval',(array)$squads)))];}
    private function normalize(array $u): array{$uuid=(string)($u['uuid']??'');$username=(string)($u['username']??'');$short=(string)($u['shortUuid']??$u['short_uuid']??'');$sub=(string)($u['subscriptionUrl']??$u['subscription_url']??'');if($sub===''&&$short!==''){$base=rtrim((string)($this->meta['subscription_base_url']??$this->base),'/');$sub=$base.'/api/sub/'.rawurlencode($short);}return['ok'=>true,'external_client_id'=>$uuid?:$username,'external_username'=>$username,'sub_id'=>$short?:null,'subscription'=>['url'=>$sub,'primary_link'=>$sub,'links'=>$sub?[$sub]:[]],'provider_response'=>$u]+$u;}
    private function isNotFound(Throwable $e): bool{return str_contains($e->getMessage(),'REMNAWAVE_HTTP_404');}
    public function createService(array $request): array{$username=(string)($request['email']??$request['external_username']??'');try{$old=$this->getClient($username);if($old)return$this->normalize($old);}catch(Throwable $e){if(!$this->isNotFound($e))throw $e;}$u=$this->unwrap($this->req('POST','/api/users',$this->createPayload($request)));return$this->normalize((array)$u);}
    public function updateService(string $externalId,array $request): array{$u=$this->getClient($externalId);$uuid=(string)($u['uuid']??$externalId);$p=['uuid'=>$uuid];if(array_key_exists('traffic_limit_bytes',$request))$p['trafficLimitBytes']=max(0,(int)$request['traffic_limit_bytes']);if(array_key_exists('expires_at',$request))$p['expireAt']=$this->isoExpiry($request);if(array_key_exists('limit_hwid',$request))$p['hwidDeviceLimit']=max(0,(int)$request['limit_hwid']);$cfg=is_array($request['provider_config']??null)?$request['provider_config']:[];if(isset($cfg['active_internal_squads']))$p['activeInternalSquads']=array_values((array)$cfg['active_internal_squads']);$res=$this->unwrap($this->req('PATCH','/api/users',$p));if(array_key_exists('enable',$request))$this->req('POST','/api/users/'.rawurlencode($uuid).'/actions/'.(!empty($request['enable'])?'enable':'disable'));return$this->normalize((array)$res);}
    public function renewService(array $request): array{return$this->updateService((string)($request['external_client_id']??$request['external_username']??''),$request);}
    public function suspendService(string $externalId): bool{$u=$this->getClient($externalId);$this->req('POST','/api/users/'.rawurlencode((string)$u['uuid']).'/actions/disable');return true;}
    public function resumeService(string $externalId): bool{$u=$this->getClient($externalId);$this->req('POST','/api/users/'.rawurlencode((string)$u['uuid']).'/actions/enable');return true;}
    public function deleteService(string $externalId): bool{$u=$this->getClient($externalId);$this->req('DELETE','/api/users/'.rawurlencode((string)$u['uuid']));return true;}
    public function getUsage(string $externalId): array{$u=$this->getClient($externalId);$traffic=is_array($u['userTraffic']??null)?$u['userTraffic']:[];$used=(int)($traffic['usedTrafficBytes']??$u['usedTrafficBytes']??$u['used_traffic_bytes']??0);$limit=(int)($u['trafficLimitBytes']??$u['traffic_limit_bytes']??0);$exp=$u['expireAt']??$u['expire_at']??null;return['used_bytes'=>$used,'traffic_limit_bytes'=>$limit,'expires_at'=>$exp?date('Y-m-d H:i:s',strtotime((string)$exp)):null,'status'=>(string)($u['status']??'unknown'),'raw'=>$u];}
    public function getSubscription(string $externalId,array $context=[]): array{$u=$this->getClient($externalId);$n=$this->normalize($u);return$n['subscription'];}
}
